[package]
name = "pointer-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
either = "1.8.1"
hashbrown = "0.13.2"
llvm-ir = { version = "0.8.2", features = ["llvm-14"] }
